### ISSUE TITLE
[Bug]: Cannot start the panel

### ISSUE THREAD

**Issue by wombat24455** [rehmatworks/fastcp#15]
### Describe the bug / issue

Hello, how can I start the panel? I installed it and it seems that it has not started as I cannot access it.

### Version

Latest (I do not know the number)

### Is it an error in the frontend (web) or in the backend (system)?

Backend (System)

### Which Ubuntu version?

20.04

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Systeminformation (run the command under this line)

```shell
Kernel: 5.13.0-1018-oracle
Python:  Python 3.8.10
PIP:  pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-01-05T14:49:56
nginx version: nginx/1.18.0 (Ubuntu)
```

**Comment by korsanye** [comment]
it's so poor coding. and it was a painful experiment.

**Comment by wombat24455** [comment]
> it's so poor coding. and it was a painful experiment.

I can understand haha, most of the projects I work on are not fantastic, I mainly use them for experience or improve them later
